plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 15

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 12
